name: Release to GitHub and NPM
on:
  workflow_dispatch:
env:
  HUSKY: 0
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repo-token: ${{ secrets.SEMANTIC_RELEASE_BOT_PAT }}
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Set explicit npm dist-tag default
        if: github.ref_name == 'main'
        run: echo "NPM_DIST_TAG=latest" >> $GITHUB_ENV
      - name: Override npm dist-tag for non-main releases
        if: github.ref_name != 'main'
        run: echo "NPM_DIST_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Release to GitHub and NPM
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_PAT }} # <-- Allows semantic-release-bot to push changes to protected branches
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN  }} # <-- Allows semantic-release to publish to npm without 2 factor auth.
          npm_config_tag: ${{ env.NPM_DIST_TAG }} # <-- For main, this is `latest.` Otherwise, `next`, `next-major`, etc. See ./.releaserc for release branch config.
        run: npx semantic-release
